apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor
  namespace: kube-system
  labels:
    app: cadvisor
spec:
  selector:
    matchLabels:
      app: cadvisor
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      restartPolicy: Always
      containers:
      - name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        resources:
          limits:
            memory: "256Mi"
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: disk
          mountPath: /dev/disk
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
      volumes:
      - name: docker
        hostPath:
          path: /var/lib/docker
          type: Directory
      - name: var-run
        hostPath:
          path: /var/run
          type: Directory
      - name: rootfs
        hostPath:
          path: /
          type: Directory
      - name: disk
        hostPath:
          path: /dev/disk
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory